// Auth.

export const GOOGLE_USER_REQUEST = 'GOOGLE_USER_REQUEST';
export const GOOGLE_USER_SUCCESS = 'GOOGLE_USER_SUCCESS';
export const GOOGLE_USER_FAILURE = 'GOOGLE_USER_FAILURE';

export const DEVICE_TOKEN_REQUEST = 'DEVICE_TOKEN_REQUEST';
export const DEVICE_TOKEN_SUCCESS = 'DEVICE_TOKEN_SUCCESS';
export const DEVICE_TOKEN_FAILURE = 'DEVICE_TOKEN_FAILURE';

// Capture.

export const RECORDING_STATUS_CHANGED = 'RECORDING_STATUS_CHANGED';
export const RECORDING_REQUESTED = 'RECORDING_REQUESTED';
export const MICROPHONE_DATA = 'MICROPHONE_DATA';

// Lessons.

export const LOAD_LESSONS_REQUEST = 'LOAD_LESSONS_REQUEST';
export const LOAD_LESSONS_SUCCESS = 'LOAD_LESSONS_SUCCESS';
export const LOAD_LESSONS_FAILURE = 'LOAD_LESSONS_FAILURE';

export const ADD_LESSON_REQUEST = 'ADD_LESSON_REQUEST';
export const ADD_LESSON_SUCCESS = 'ADD_LESSON_SUCCESS';
export const ADD_LESSON_FAILURE = 'ADD_LESSON_FAILURE';

// Sockets.

export const SOCKET_CONNECTING = 'SOCKET_CONNECTING';
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';
export const SOCKET_ERROR = 'SOCKET_ERROR';
