// Auth.

export const GOOGLE_USER_REQUEST = 'GOOGLE_USER_REQUEST';
export const GOOGLE_USER_SUCCESS = 'GOOGLE_USER_SUCCESS';
export const GOOGLE_USER_FAILURE = 'GOOGLE_USER_FAILURE';

export const DEVICE_TOKEN_REQUEST = 'DEVICE_TOKEN_REQUEST';
export const DEVICE_TOKEN_SUCCESS = 'DEVICE_TOKEN_SUCCESS';
export const DEVICE_TOKEN_FAILURE = 'DEVICE_TOKEN_FAILURE';

// Capture.

export const RECORDING_STATUS_CHANGED = 'RECORDING_STATUS_CHANGED';
export const RECORDING_STATUS_CHANGING = 'RECORDING_STATUS_CHANGING';
export const USER_REQUEST_RECORDING = 'USER_REQUEST_RECORDING';
export const MICROPHONE_DATA_RECEIVED = 'MICROPHONE_DATA_RECEIVED';
export const SERVER_TERMINATED_CAPTURE = 'SERVER_TERMINATED_CAPTURE';

export const TRANSCRIPT_RECEIVED = 'TRANSCRIPT_RECEIVED';
export const SPEECH_ENDED_BY_SERVER = 'SPEECH_ENDED_BY_SERVER';
export const ANSWER_RECEIVED = 'ANSWER_RECEIVED';

// Lessons.

export const LOAD_LESSONS_REQUEST = 'LOAD_LESSONS_REQUEST';
export const LOAD_LESSONS_SUCCESS = 'LOAD_LESSONS_SUCCESS';
export const LOAD_LESSONS_FAILURE = 'LOAD_LESSONS_FAILURE';

export const ADD_LESSON_REQUEST = 'ADD_LESSON_REQUEST';
export const ADD_LESSON_SUCCESS = 'ADD_LESSON_SUCCESS';
export const ADD_LESSON_FAILURE = 'ADD_LESSON_FAILURE';

// Sockets.

export const CONNECT_SOCKET = 'CONNECT_SOCKET';
export const SEND_AUDIO_DATA = 'SEND_AUDIO_DATA';
export const SEND_SAMPLE_RATE = 'SEND_SAMPLE_RATE';
export const SEND_END_OF_SPEECH = 'SEND_END_OF_SPEECH';

export const SOCKET_IS_READY_FOR_AUDIO = 'SOCKET_IS_READY_FOR_AUDIO';

export const SOCKET_CONNECTING = 'SOCKET_CONNECTING';
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';
export const SOCKET_ERROR = 'SOCKET_ERROR';
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED';

// Wake word
export const WAKE_WORD_RECEIVED = 'WAKE_WORD_RECEIVED';
export const INITIALIZE_WAKE_WORD = 'INITIALIZE_WAKE_WORD';
export const WAKE_WORD_DETECTOR_READY = 'WAKE_WORD_DETECTOR_READY';
export const SEND_WAKE_WORD_AUDIO = 'SEND_WAKE_WORD_AUDIO';

export const WAKE_WORD_LISTENING_STATUS_CHANGED = 'WAKE_WORD_LISTENING_STATUS_CHANGED';
