// Auth.

export const GOOGLE_USER_REQUEST = 'GOOGLE_USER_REQUEST';
export const GOOGLE_USER_FAILURE = 'GOOGLE_USER_FAILURE';
export const GOOGLE_USER_SUCCESS = 'GOOGLE_USER_SUCCESS';

export const SCOUT_USER_REQUEST = 'SCOUT_USER_REQUEST';
export const SCOUT_USER_FAILURE = 'SCOUT_USER_FAILURE';
export const SCOUT_USER_SUCCESS = 'SCOUT_USER_SUCCESS';

// Lessons.

export const LESSONS_REQUEST = 'LESSONS_REQUEST';
export const LESSONS_FAILURE = 'LESSONS_FAILURE';
export const LESSONS_SUCCESS = 'LESSONS_SUCCESS';
